# Generated by Django 5.2.15 on 2026-06-20 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/%Y-%m-%d/')),
                ('description', models.TextField()),
                ('date_type', models.IntegerField(choices=[(0, 'Обычная дата'), (1, 'Номер дня недели в месяце'), (2, 'Номер дня в году')], default=0)),
                ('month', models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=1, verbose_name='Месяц')),
                ('day', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=1, verbose_name='День месяца')),
                ('day_of_the_year', models.IntegerField(default=0, verbose_name='Номер дня в году')),
                ('week_of_the_month', models.IntegerField(choices=[(0, 'Не выбрано'), (1, 'Первая неделя месяца'), (2, 'Вторая неделя месяца'), (3, 'Третья неделя месяца'), (4, 'Четвертая неделя месяца')], default=0, verbose_name='Номер недели в месяце')),
                ('week_day', models.IntegerField(choices=[(0, 'Не выбрано'), (1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], default=0, verbose_name='День недели')),
                ('publication_date', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Следующая дата праздника')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PostCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y-%m-%d/')),
                ('publication_date', models.DateTimeField(auto_now=True)),
                ('informer_x', models.IntegerField(default=0)),
                ('informer_y', models.IntegerField(default=0)),
                ('image_width', models.IntegerField(default=0)),
                ('image_height', models.IntegerField(default=0)),
                ('informer_font', models.CharField(default='', max_length=50)),
                ('is_informer', models.BooleanField(default=False)),
                ('holiday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.holiday')),
            ],
        ),
    ]
